/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuivisIndexRouteImport } from './routes/suivis.index'
import { Route as ProspectionsIndexRouteImport } from './routes/prospections.index'
import { Route as DemandesIndexRouteImport } from './routes/demandes.index'
import { Route as SuivisIdRouteImport } from './routes/suivis.$id'
import { Route as ProspectionsIdRouteImport } from './routes/prospections.$id'
import { Route as DemandesIdRouteImport } from './routes/demandes.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuivisIndexRoute = SuivisIndexRouteImport.update({
  id: '/suivis/',
  path: '/suivis/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectionsIndexRoute = ProspectionsIndexRouteImport.update({
  id: '/prospections/',
  path: '/prospections/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandesIndexRoute = DemandesIndexRouteImport.update({
  id: '/demandes/',
  path: '/demandes/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuivisIdRoute = SuivisIdRouteImport.update({
  id: '/suivis/$id',
  path: '/suivis/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectionsIdRoute = ProspectionsIdRouteImport.update({
  id: '/prospections/$id',
  path: '/prospections/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandesIdRoute = DemandesIdRouteImport.update({
  id: '/demandes/$id',
  path: '/demandes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/demandes/$id': typeof DemandesIdRoute
  '/prospections/$id': typeof ProspectionsIdRoute
  '/suivis/$id': typeof SuivisIdRoute
  '/demandes/': typeof DemandesIndexRoute
  '/prospections/': typeof ProspectionsIndexRoute
  '/suivis/': typeof SuivisIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/demandes/$id': typeof DemandesIdRoute
  '/prospections/$id': typeof ProspectionsIdRoute
  '/suivis/$id': typeof SuivisIdRoute
  '/demandes': typeof DemandesIndexRoute
  '/prospections': typeof ProspectionsIndexRoute
  '/suivis': typeof SuivisIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/demandes/$id': typeof DemandesIdRoute
  '/prospections/$id': typeof ProspectionsIdRoute
  '/suivis/$id': typeof SuivisIdRoute
  '/demandes/': typeof DemandesIndexRoute
  '/prospections/': typeof ProspectionsIndexRoute
  '/suivis/': typeof SuivisIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/demandes/$id'
    | '/prospections/$id'
    | '/suivis/$id'
    | '/demandes/'
    | '/prospections/'
    | '/suivis/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/demandes/$id'
    | '/prospections/$id'
    | '/suivis/$id'
    | '/demandes'
    | '/prospections'
    | '/suivis'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/demandes/$id'
    | '/prospections/$id'
    | '/suivis/$id'
    | '/demandes/'
    | '/prospections/'
    | '/suivis/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  DemandesIdRoute: typeof DemandesIdRoute
  ProspectionsIdRoute: typeof ProspectionsIdRoute
  SuivisIdRoute: typeof SuivisIdRoute
  DemandesIndexRoute: typeof DemandesIndexRoute
  ProspectionsIndexRoute: typeof ProspectionsIndexRoute
  SuivisIndexRoute: typeof SuivisIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suivis/': {
      id: '/suivis/'
      path: '/suivis'
      fullPath: '/suivis/'
      preLoaderRoute: typeof SuivisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospections/': {
      id: '/prospections/'
      path: '/prospections'
      fullPath: '/prospections/'
      preLoaderRoute: typeof ProspectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demandes/': {
      id: '/demandes/'
      path: '/demandes'
      fullPath: '/demandes/'
      preLoaderRoute: typeof DemandesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suivis/$id': {
      id: '/suivis/$id'
      path: '/suivis/$id'
      fullPath: '/suivis/$id'
      preLoaderRoute: typeof SuivisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospections/$id': {
      id: '/prospections/$id'
      path: '/prospections/$id'
      fullPath: '/prospections/$id'
      preLoaderRoute: typeof ProspectionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demandes/$id': {
      id: '/demandes/$id'
      path: '/demandes/$id'
      fullPath: '/demandes/$id'
      preLoaderRoute: typeof DemandesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  DemandesIdRoute: DemandesIdRoute,
  ProspectionsIdRoute: ProspectionsIdRoute,
  SuivisIdRoute: SuivisIdRoute,
  DemandesIndexRoute: DemandesIndexRoute,
  ProspectionsIndexRoute: ProspectionsIndexRoute,
  SuivisIndexRoute: SuivisIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
