/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as Creation_prospectionRouteImport } from './routes/creation_prospection'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuivisIndexRouteImport } from './routes/suivis.index'
import { Route as ProspectionsIndexRouteImport } from './routes/prospections.index'
import { Route as DemandesIndexRouteImport } from './routes/demandes.index'
import { Route as SuivisIdRouteImport } from './routes/suivis.$id'
import { Route as ProspectionsIdRouteImport } from './routes/prospections.$id'
import { Route as DemandesIdRouteImport } from './routes/demandes.$id'
import { Route as Creation_userRouteImport } from './routes/creation_user'
import { Route as UsersIndexRouteImport } from './routes/users.index'
import { Route as UsersIdRouteImport } from './routes/users.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const Creation_prospectionRoute = Creation_prospectionRouteImport.update({
  id: '/creation_prospection',
  path: '/creation_prospection',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuivisIndexRoute = SuivisIndexRouteImport.update({
  id: '/suivis/',
  path: '/suivis/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectionsIndexRoute = ProspectionsIndexRouteImport.update({
  id: '/prospections/',
  path: '/prospections/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandesIndexRoute = DemandesIndexRouteImport.update({
  id: '/demandes/',
  path: '/demandes/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuivisIdRoute = SuivisIdRouteImport.update({
  id: '/suivis/$id',
  path: '/suivis/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectionsIdRoute = ProspectionsIdRouteImport.update({
  id: '/prospections/$id',
  path: '/prospections/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandesIdRoute = DemandesIdRouteImport.update({
  id: '/demandes/$id',
  path: '/demandes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const Creation_userRoute = Creation_userRouteImport.update({
  id: '/creation_user',
  path: '/creation_user',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIdRoute = UsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/creation_prospection': typeof Creation_prospectionRoute
  '/creation_user': typeof Creation_userRoute
  '/login': typeof LoginRoute
  '/users/$id': typeof UsersIdRoute
  '/demandes/$id': typeof DemandesIdRoute
  '/prospections/$id': typeof ProspectionsIdRoute
  '/suivis/$id': typeof SuivisIdRoute
  '/demandes/': typeof DemandesIndexRoute
  '/prospections/': typeof ProspectionsIndexRoute
  '/suivis/': typeof SuivisIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/creation_prospection': typeof Creation_prospectionRoute
  '/creation_user': typeof Creation_userRoute
  '/login': typeof LoginRoute
  '/users/$id': typeof UsersIdRoute
  '/demandes/$id': typeof DemandesIdRoute
  '/prospections/$id': typeof ProspectionsIdRoute
  '/suivis/$id': typeof SuivisIdRoute
  '/demandes': typeof DemandesIndexRoute
  '/prospections': typeof ProspectionsIndexRoute
  '/suivis': typeof SuivisIndexRoute
  '/users': typeof UsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/creation_prospection': typeof Creation_prospectionRoute
  '/creation_user': typeof Creation_userRoute
  '/login': typeof LoginRoute
  '/users/$id': typeof UsersIdRoute
  '/demandes/$id': typeof DemandesIdRoute
  '/prospections/$id': typeof ProspectionsIdRoute
  '/suivis/$id': typeof SuivisIdRoute
  '/demandes/': typeof DemandesIndexRoute
  '/prospections/': typeof ProspectionsIndexRoute
  '/suivis/': typeof SuivisIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/creation_prospection'
    | '/creation_user'
    | '/login'
    | '/users/$id'
    | '/demandes/$id'
    | '/prospections/$id'
    | '/suivis/$id'
    | '/demandes/'
    | '/prospections/'
    | '/suivis/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/creation_prospection'
    | '/creation_user'
    | '/login'
    | '/users/$id'
    | '/demandes/$id'
    | '/prospections/$id'
    | '/suivis/$id'
    | '/demandes'
    | '/prospections'
    | '/suivis'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/creation_prospection'
    | '/creation_user'
    | '/login'
    | '/users/$id'
    | '/demandes/$id'
    | '/prospections/$id'
    | '/suivis/$id'
    | '/demandes/'
    | '/prospections/'
    | '/suivis/'
    | '/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Creation_prospectionRoute: typeof Creation_prospectionRoute
  Creation_userRoute: typeof Creation_userRoute
  LoginRoute: typeof LoginRoute
  UsersIdRoute: typeof UsersIdRoute
  DemandesIdRoute: typeof DemandesIdRoute
  ProspectionsIdRoute: typeof ProspectionsIdRoute
  SuivisIdRoute: typeof SuivisIdRoute
  DemandesIndexRoute: typeof DemandesIndexRoute
  ProspectionsIndexRoute: typeof ProspectionsIndexRoute
  SuivisIndexRoute: typeof SuivisIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creation_prospection': {
      id: '/creation_prospection'
      path: '/creation_prospection'
      fullPath: '/creation_prospection'
      preLoaderRoute: typeof Creation_prospectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creation_user': {
      id: '/creation_user'
      path: '/creation_user'
      fullPath: '/creation_user'
      preLoaderRoute: typeof Creation_userRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suivis/': {
      id: '/suivis/'
      path: '/suivis'
      fullPath: '/suivis/'
      preLoaderRoute: typeof SuivisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospections/': {
      id: '/prospections/'
      path: '/prospections'
      fullPath: '/prospections/'
      preLoaderRoute: typeof ProspectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demandes/': {
      id: '/demandes/'
      path: '/demandes'
      fullPath: '/demandes/'
      preLoaderRoute: typeof DemandesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suivis/$id': {
      id: '/suivis/$id'
      path: '/suivis/$id'
      fullPath: '/suivis/$id'
      preLoaderRoute: typeof SuivisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospections/$id': {
      id: '/prospections/$id'
      path: '/prospections/$id'
      fullPath: '/prospections/$id'
      preLoaderRoute: typeof ProspectionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demandes/$id': {
      id: '/demandes/$id'
      path: '/demandes/$id'
      fullPath: '/demandes/$id'
      preLoaderRoute: typeof DemandesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$id': {
      id: '/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof UsersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Creation_prospectionRoute: Creation_prospectionRoute,
  Creation_userRoute: Creation_userRoute,
  LoginRoute: LoginRoute,
  UsersIdRoute: UsersIdRoute,
  DemandesIdRoute: DemandesIdRoute,
  ProspectionsIdRoute: ProspectionsIdRoute,
  SuivisIdRoute: SuivisIdRoute,
  DemandesIndexRoute: DemandesIndexRoute,
  ProspectionsIndexRoute: ProspectionsIndexRoute,
  SuivisIndexRoute: SuivisIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
